# Generated by Django 3.0.5 on 2020-04-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ticketmaster id')),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('promoter_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='scrappers.Event')),
            ],
        ),
    ]
